### ISSUE TITLE
pyphi execution hangs after outputting one line

### ISSUE THREAD

**Issue by nickums** [wmayner/pyphi#112]
Using the exact code in  /github.com/wmayner/pyphi  on windows10 python 3.8,  the execution hangs after producing this line:

Computing concepts:   0%|          | 0/3 [00:00<?, ?it/s]

**Comment by isacdaavid** [comment]
Hi.

What function are you calling here? How big is the system you are analyzing? (there's a big chance it's still computing something).
If you can provide a working example for us to reproduce, that'd be ideal.

**Comment by nickums** [comment]
sorry my question was so badly worded, don't remember what the script was. In any case I see native windows is not a good platform for pyphi so I abandon takig a look at it.
Thanks for trying to help me.
