### ISSUE TITLE
Couldn't find collections.abc

### ISSUE THREAD

**Issue by fischerdom** [wmayner/pyphi#20]
Hey man,

I am not sure if I did something wrong on my Ubuntu-Server, but I had to add `import collections.abc` to the file `.../pyphi/models/cuts.py`.

Cheers,
Dominik

**Comment by wmayner** [comment]
Hey Dominik!

That's strange. What Python version are you using, and what version of PyPhi? And were you doing anything in particular when the error came up, or just `import pyphi`?

**Comment by fischerdom** [comment]
Yes, sounds strange to me, too. I am using Python 3.4. i just used my
common phi calculations for Markov brains.

William Mayner <notifications@github.com> schrieb am Mi., 6. Juni 2018,
20:35:

**Comment by wmayner** [comment]
All the tests on Travis are passing for Python 3.4, 3.5, and 3.6 so it's probably something specific to your system, though I have no guess as to why, because this shouldn't be system-dependent.

Do you know which line is throwing the error? Is it the line where you `import pyphi` or something else?

**Comment by rlmv** [comment]
Seems related to https://bugs.python.org/issue20784#msg213126. Also see https://hg.python.org/cpython/rev/d575398d1916. Not sure whether this applies to some 3.4 minor releases and not others, but I think the easy fix is to just use `collections.Sequence` instead of `collections.abc.Sequence`.

**Comment by rlmv** [comment]
669f1b5 should fix this. I'm closing this issue now - @fischerdom, can you reopen if it is still an issue?

**Comment by fischerdom** [comment]
Alright, thanks for your help!
