### ISSUE TITLE
Applying IIT to the Game of Life

### ISSUE THREAD

**Issue by void4** [wmayner/pyphi#24]
https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life

When a cell is alive, it has 140 possible predecessor patterns, if it is dead, 372.

Can one apply IIT to visualize phi values and subject boundaries?

I found one of your previous publications which applied IIT to elementary cellular automata: https://www.mdpi.com/1099-4300/17/8/5472

Are you aware of anyone who considered the 2D, 3D or even [smooth](https://www.youtube.com/watch?v=KJe9H6qS82I)-case?

Edit: From your answer [here](https://github.com/wmayner/pyphi/issues/17#issuecomment-332577154) I can see that this problem seems to be currently computationally intractable, even in regular systems such as these.

**Comment by wmayner** [comment]
Closing; see #25.
