### ISSUE TITLE
IIT subject boundaries: Voronoi or candles?

### ISSUE THREAD

**Issue by void4** [wmayner/pyphi#25]
When applying IIT to our universe, do the subject boundaries look more like [Voronoi diagrams](https://en.wikipedia.org/wiki/Voronoi_diagram
) (the entire space is filled)
![image](https://user-images.githubusercontent.com/11392207/52159316-c1d48a80-26a2-11e9-980d-f310c27d53cc.png)

or are there "non-subjective" spaces inbetween
![image](https://user-images.githubusercontent.com/11392207/52159311-b97c4f80-26a2-11e9-8f64-860e08cb8740.png)?

**Comment by wmayner** [comment]
This is a complex question, but the short answer is that if one were to apply the IIT algorithm to the universe (specifically, the [`pyphi.compute.network.condensed()`](https://pyphi.readthedocs.io/en/stable/api/compute.network.html#pyphi.compute.network.condensed)  function), there would almost certainly be regions that are not part of any complex; that is, the result would look more like the second image.

We prefer to use the GitHub issues page for specific issues with PyPhi, so I'll close this, but please feel free to join our [mailing list](https://groups.google.com/forum/#!forum/pyphi-users) for further discussion.

**Comment by void4** [comment]
Thank you!
