### ISSUE TITLE
pyphi-users mailing list

### ISSUE THREAD

**Issue by peepo** [wmayner/pyphi#32]
as per #25

I tried logging in to my google groups, and using URL:
https://groups.google.com/forum/#!forum/pyphi-users

I received a message that I did not have permission to view content

I did a search for pyphi-users, google reports not found

however I did not find a way to request membership,

I sent you an email, no response as yet!

**Comment by wmayner** [comment]
It seems Google recently changed how group visibility works. This should be fixed now.

**Comment by peepo** [comment]
okay tx, have applied to join, please accept, different email to github....
