### ISSUE TITLE
Error when trying to receive TPM using json

### ISSUE THREAD

**Issue by DiegoBneiNoah** [wmayner/pyphi#39]
HH,

i have open ipython, done import numpy as np and import pyphi. And then I have done
`network = pyphi.network.from_json ('/home/ diego/ NET/network.json')`

But when I run network.tpm I get the following error message below:
```

In [5]: network.tpm
----------------------------------------
AttributeErrorTraceback (most recent call last)
<ipython-input-5-044da6143242> in <module>
----> 1 network.tpm

AttributeError: 'dict' object has no attribute 'tpm'
```
What am I doing wrong? Should I get the TPM instead of the error message, or not?

**Comment by wmayner** [comment]
Hi, 

Did you solve this issue? I could not reproduce it.
